import jsPDF from 'jspdf';

export class PDFGenerator {
  static async generatePDF(result: any): Promise<Buffer> {
    const doc = new (jsPDF as any)();
    
    // Set font for better text rendering
    doc.setFont('helvetica');
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(`${result.vendor} Conversation`, 20, 30);
    
    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Parsed at: ${result.parsedAt}`, 20, 45);
    
    if (result.metadata?.url) {
      doc.text(`URL: ${result.metadata.url}`, 20, 52);
    }
    
    if (result.metadata?.model) {
      doc.text(`Model: ${result.metadata.model}`, 20, 59);
    }
    
    // Messages
    let yPosition = 75;
    const pageHeight = doc.internal.pageSize.height;
    const marginBottom = 20;
    const lineHeight = 7;
    
    for (const message of result.messages) {
      // Check if we need a new page
      if (yPosition > pageHeight - marginBottom - 30) {
        doc.addPage();
        yPosition = 30;
      }
      
      // Role header
      doc.setFontSize(12);
      if (message.role === 'user') {
        doc.setTextColor(0, 102, 204); // Blue for user
        doc.text('User:', 20, yPosition);
      } else {
        doc.setTextColor(34, 139, 34); // Green for assistant
        doc.text('Assistant:', 20, yPosition);
      }
      
      yPosition += lineHeight + 3;
      
      // Message content
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      
      // Split text into lines that fit the page width
      const pageWidth = doc.internal.pageSize.width;
      const maxWidth = pageWidth - 40; // 20px margin on each side
      const lines = doc.splitTextToSize(message.content, maxWidth);
      
      for (const line of lines) {
        // Check if we need a new page
        if (yPosition > pageHeight - marginBottom) {
          doc.addPage();
          yPosition = 30;
        }
        
        doc.text(line, 20, yPosition);
        yPosition += lineHeight;
      }
      
      // Add spacing between messages
      yPosition += 10;
      
      // Add separator line
      if (yPosition < pageHeight - marginBottom - 5) {
        doc.setLineWidth(0.1);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, yPosition, pageWidth - 20, yPosition);
        yPosition += 10;
      }
    }
    
    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${i} of ${totalPages} - Generated by Yanked.Chat`, 
        20, 
        pageHeight - 10
      );
    }
    
    // Return as Buffer
    const pdfOutput = doc.output('arraybuffer');
    return Buffer.from(pdfOutput);
  }
  
  static formatAsStyledPDF(result: any): Buffer {
    const doc = new (jsPDF as any)();
    
    // Enhanced styling with better typography
    doc.setFont('helvetica');
    
    // Header with gradient effect simulation
    doc.setFillColor(255, 87, 34); // Orange gradient start
    doc.rect(0, 0, doc.internal.pageSize.width, 40, 'F');
    
    // Title
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text(`${result.vendor} Conversation`, 20, 25);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text('Extracted with Yanked.Chat', 20, 35);
    
    // Metadata box
    let yPos = 55;
    doc.setFillColor(248, 249, 250);
    doc.rect(20, yPos, doc.internal.pageSize.width - 40, 25, 'F');
    
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(`Extracted: ${new Date(result.parsedAt).toLocaleString()}`, 25, yPos + 8);
    doc.text(`Messages: ${result.messages.length}`, 25, yPos + 16);
    
    if (result.metadata?.model) {
      doc.text(`Model: ${result.metadata.model}`, 120, yPos + 8);
    }
    
    yPos = 90;
    
    // Messages with enhanced styling
    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;
    
    for (let i = 0; i < result.messages.length; i++) {
      const message = result.messages[i];
      
      // Check for page break
      if (yPos > pageHeight - 60) {
        doc.addPage();
        yPos = 30;
      }
      
      // Message bubble background
      const bubbleColor = message.role === 'user' ? [232, 245, 255] as const : [248, 252, 255] as const;
      const borderColor = message.role === 'user' ? [59, 130, 246] as const : [34, 197, 94] as const;
      
      // Estimate content height
      const maxWidth = pageWidth - 80;
      const lines = doc.splitTextToSize(message.content, maxWidth);
      const contentHeight = lines.length * 5 + 20;
      
      // Draw message container
      doc.setFillColor(bubbleColor[0], bubbleColor[1], bubbleColor[2]);
      doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.setLineWidth(0.5);
      doc.roundedRect(20, yPos, pageWidth - 40, contentHeight, 3, 3, 'FD');
      
      // Role badge
      doc.setFillColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.roundedRect(25, yPos + 5, 60, 12, 2, 2, 'F');
      
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      const roleText = message.role === 'user' ? 'User' : 'Assistant';
      doc.text(roleText, 30, yPos + 13);
      
      // Message content
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      
      let lineY = yPos + 25;
      for (const line of lines) {
        doc.text(line, 30, lineY);
        lineY += 5;
      }
      
      yPos += contentHeight + 15;
    }
    
    // Footer on all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text(
        `yanked.chat - AI Conversation Extractor | Page ${i} of ${totalPages}`, 
        20, 
        pageHeight - 10
      );
    }
    
    const pdfOutput = doc.output('arraybuffer');
    return Buffer.from(pdfOutput);
  }
}